- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      io.kompose.service: {{ .Values.service.serviceName }}
    name: {{ .Values.service.serviceName }}
  spec:
    replicas: {{ .Values.replicaCount }}
    selector:
      matchLabels:
        io.kompose.service: {{ .Values.service.serviceName }}
    strategy: {}
    template:
      metadata:
        labels:
          io.kompose.service: {{ .Values.service.serviceName }}
      spec:
        containers:
          - env:
              - name: {{ .Values.environment.name }}
                value: {{ .Values.environment.value }}
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            name: {{ .Values.service.serviceName }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
              - containerPort: {{ .Values.service.port }}
            resources: {}
        restartPolicy: {{ .Values.restartPolicy }}
  status: {}
