apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.labels }}: {{ .Values.service.serviceName }}
  name: {{ .Values.service.serviceName }}
spec:
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{ .Values.labels }}: {{ .Values.service.serviceName }}
status:
  loadBalancer: {}
